# Generated by Django 2.2.24 on 2021-06-20 04:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='about',
            field=models.CharField(default=datetime.datetime(2021, 6, 20, 4, 57, 23, 374671, tzinfo=utc), max_length=256),
            preserve_default=False,
        ),
    ]
