# Generated by Django 2.2.24 on 2021-06-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('born', models.DateField()),
                ('email', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('nationality', models.CharField(max_length=8)),
                ('is_activate', models.BooleanField(default=True)),
            ],
        ),
    ]
