# Generated by Django 2.2.24 on 2021-06-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_about'),
        ('students', '0004_auto_20210620_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(related_name='courses', to='courses.Course'),
        ),
    ]
