# Generated by Django 2.2.24 on 2021-06-20 22:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_student_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='url_image',
            field=models.CharField(default=datetime.datetime(2021, 6, 20, 22, 47, 56, 131203, tzinfo=utc), max_length=128),
            preserve_default=False,
        ),
    ]
